services:
  minecraft:
    # Docker image is configurable per config file:
    image: ${MINECRAFT_IMAGE}
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024
    restart: unless-stopped
    # All labels are defined in the template: docker-compose.instance.yaml
    labels: []
    environment:
      - EULA=TRUE
    ports:
      - "25565:25565"
